### ISSUE TITLE
Passing data into tests

### ISSUE THREAD

**Issue by rdooh** [Huddle/PhantomFlow#17]
This is awesome by the way...

I'm successfully running this inside an Express app. My aim is to integrate this into a small local service for testing and retesting various sites.  Some of those sites require u:p credentials to log in.  Although I can hardcode them into the tests (with casper.setHttpAuth()), I'd rather be able to pass these in from the outside.  Possible to do something like '--flowargs=...' or similar?  Essentially, I need to get something user-supplied from the node/Express app req.params into the individual tests... is this possible in the current setup, or a possible enhancement?

Many thanks,
Rob

**Comment by jamescryer** [comment]
casperArgs (string[]): optional arguments to pass into casper and PhantomJS, such as --ignore-ssl-errors=true
