### ISSUE TITLE
config mismatchTolerance of phantomcss

### ISSUE THREAD

**Issue by jacek213** [Huddle/PhantomFlow#28]
Hello,

How can I change the value of mismatchTolerance option belonging to phantomcss? I use grunt-phantomflow to be exact.

**Comment by jamescryer** [comment]
Its not currently supported.  You can work around it by hard-coding the mismatchTolerance option here https://github.com/Huddle/PhantomFlow/blob/master/lib/phantomCSSAdaptor.js

I'll accept a PR that threads the value through from PhantomFlow/grunt-phantomflow

**Comment by jacekgrzybowski** [comment]
My current workaround is to create a file `config.js` in `casper/include` directory, containing:

    phantomCSS.update({
        "mismatchTolerance": 5
    });

I will think about the PR when I happen to have some free time.
