### ISSUE TITLE
Tests files position

### ISSUE THREAD

**Issue by yoyurec** [Huddle/PhantomFlow#45]
Trying to run on my project structure:
```
front/modules/name1/test/name1.test.js
front/modules/name2/test/name2.test.js
```

Script options: `tests: 'front/modules/**/test'` works ok, all files processed, but result doesn't works (((

Looks like `tests` var used alot, maybe it's better to split? For ex.:
```
`base`: 'whatever'
 `tests: 'front/modules/**/test'`
```

**Comment by jamescryer** [comment]
The `tests` option should set the root directory that contains your tests.  PhantomFlow will recurse into that directory to find all your tests.

You can use the `testFileExtension` options to specify the extension of your test files; by default it looks for all files that match `.test.js`.

e.g.

```
{
  tests: 'project/phantomdflowtests',
  testFileExtension: '.phantomflow.test.js'
}
```
