### ISSUE TITLE
Question - is it possible to pass data/arguments down to individual tests from script starting phantomflow

### ISSUE THREAD

**Issue by bryanrasmussen** [Huddle/PhantomFlow#52]
Basically I want to do some stuff on top of phantomflow, and to have logic branching based on command line arguments as to whether one runs production or integration tests against a remote url or on the local server. 

The easiest for me would be if I can pass my arguments all the way down to the tests that are started by casperjs. 

Is that possible or should I use environmental variables instead to do the branching?

**Comment by jamescryer** [comment]
You can use `casperArgs` option (see README) then in your test you can use `casper.cli.get("foo")`

**Comment by bryanrasmussen** [comment]
ah ok. that is good thanks.
