### ISSUE TITLE
In which method to compare two pictures?

### ISSUE THREAD

**Issue by MarvinLiuMing** [Huddle/PhantomFlow#55]
I cannot find it.

**Comment by jamescryer** [comment]
PhantomCSS has a method to compare two images. See https://github.com/Huddle/PhantomCSS#compare-the-images-when-and-how-you-want

```
phantomcss.compareExplicit(['/dialog.diff.png', '/header.diff.png']);
```

Phantomflow just defines the structured DSL and generates the visualisation for the tests.

**Comment by MarvinLiuMing** [comment]
@jamescryer thanks  a lot
